main: jp.ogiwara.nukkit.oauth.SampleOAuth
name: SampleOAuth
version: "Final"
api: ["1.0.0"]
description: Sample OAuth plugin
commands:
  register:
    description: パスワードの登録
    usage: /register <password>
  login:
    description: ログイン
    usage: /login <password>